const OfferLetterData = [
  {
    label: "Company Name",
    name: "company_Name",
    id: "001",
    placeholder: "Enter Company Name",
    className: "Company_Name_div",
    //error: "",
    //errorMessage: "",
    type: "text",
    value: "________",
  },
  {
    label: "HR Name",
    name: "hR_Name",
    id: "002",
    placeholder: "Enter HR Name",
    className: "HR_Name_div",
    //error: "",
    //errorMessage: "",
    type: "text",
    value: "________",
  },
  {
    label: "Ref No.",
    name: "ref_No",
    id: "003",
    placeholder: "Enter Ref No",
    className: "Ref_No_div",
    //error: "",
    //errorMessage: "",
    type: "",
    value: "________",
  },
  {
    label: "Date of Issue",
    name: "date_of_Issue",
    id: "004",
    placeholder: "dd/mm/yyyy",
    className: "Date_of_Issue_div",
    //error: "",
    //errorMessage: "Enter date",
    type: "date",
    value: "________",
  },
  {
    label: "Employee Name",
    name: "employee_Name",
    id: "005",
    placeholder: "Enter Employee Name",
    className: "Employee_Name_div",
    //error: "",
    //errorMessage: "",
    type: "text",
    value: "________",
  },
  {
    label: "Position",
    name: "position",
    id: "006",
    placeholder: "Enter Position",
    className: "Position_div",
    //error: "",
    //errorMessage: "",
    type: "text",
    value: "________",
  },
  {
    label: "Compensation",
    name: "compensation",
    id: "007",
    placeholder: "Enter Compensation",
    className: "Compensation_div",
    //error: "",
    //errorMessage: "",
    type: "text",
    value: "________",
  },
  {
    label: "Date of Joining",
    name: "date_of_Joining",
    id: "008",
    placeholder: "dd/mm/yyyy",
    className: "Date_of_Joining_div",
    //error: "",
    //errorMessage: "Enter date",
    type: "date",
    value: "________",
  },
];

export default OfferLetterData;

/*{ name: "" },
  { className: "" },
  { type: "" },
  { placeholder: "" },
  { innerRef: "" },
  { error: "" },
  { errorMessage: "" },*/
